-- Tabela de leads Santa Clara (interesses em veículos), alimentada pelo export do CRM.
CREATE TABLE IF NOT EXISTS public."Interesse_SantaClara" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "Nome" TEXT,
  "Numero" TEXT,
  "Interesse" TEXT,
  "Anotação" TEXT
);

ALTER TABLE public."Interesse_SantaClara" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read" ON public."Interesse_SantaClara" FOR SELECT USING (true);
CREATE POLICY "Public insert" ON public."Interesse_SantaClara" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update" ON public."Interesse_SantaClara" FOR UPDATE USING (true);
CREATE POLICY "Public delete" ON public."Interesse_SantaClara" FOR DELETE USING (true);

CREATE INDEX IF NOT EXISTS idx_santaclara_interesse ON public."Interesse_SantaClara" ("Interesse");
